apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerney-frontend
  namespace: jerney
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jerney-frontend
  template:
    metadata:
      labels:
        app: jerney-frontend
    spec:
      containers:
      - name: frontend
        image: harshithgowda45/jerney-frontend:v1
        ports:
        - containerPort: 80
